export { Header } from './Header'
export { Footer } from './Footer'
export { Marquee } from './Marquee'
export type { MarqueeProps } from './Marquee'
export { default as MarqueeBar } from './MarqueeBar'
export { FloatingBadge } from './FloatingBadge'
